repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks: 
      - id: mypy
        additional_dependencies: [typing_extensions]

  # Tests should be run separately as part of CI
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: poetry run pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true 