repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        name: ruff check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest -q -m "not property"
        language: system
        pass_filenames: false
        always_run: true
      - id: check-interface
        name: Check interface compliance
        entry: scripts/check_interface.py
        language: python
        args: ["HEAD"]
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        language: python
        entry: poetry run mypy
        args: [--config-file=pyproject.toml]
        exclude: ^(docs/|.*/templates/|app\.py|.*/generated/)
