"""initial schema

Revision ID: efd4449df5b5
Revises:
Create Date: 2025-07-08 21:56:03.841519

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efd4449df5b5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "joblog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_joblog_job_id"), "joblog", ["job_id"], unique=False)
    op.create_index(op.f("ix_joblog_timestamp"), "joblog", ["timestamp"], unique=False)
    op.create_table(
        "spec",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spec_name"), "spec", ["name"], unique=True)
    op.create_table(
        "artefact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artefact_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("spec_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spec_id"],
            ["spec.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artefact_artefact_type"), "artefact", ["artefact_type"], unique=False)
    op.create_table(
        "benchmark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("artefact_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artefact_id"],
            ["artefact.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("benchmark")
    op.drop_index(op.f("ix_artefact_artefact_type"), table_name="artefact")
    op.drop_table("artefact")
    op.drop_index(op.f("ix_spec_name"), table_name="spec")
    op.drop_table("spec")
    op.drop_index(op.f("ix_joblog_timestamp"), table_name="joblog")
    op.drop_index(op.f("ix_joblog_job_id"), table_name="joblog")
    op.drop_table("joblog")
    # ### end Alembic commands ###
