name: algo-agent
on:
  push:
    paths:
      - "specs/**"
      - "spec_builder/**"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Start Ollama (optional – comment out to use OpenAI)
        if: ${{ env.LLM_BACKEND == 'ollama' }}
        uses: ollama/ollama-action@v1
        with:
          model: ${{ env.OLLAMA_MODEL }}

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run agent
        env:
          LLM_BACKEND: ${{ secrets.LLM_BACKEND || 'openai' }}
          OLLAMA_MODEL: ${{ secrets.OLLAMA_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/run_algo_agent.py
